* Changelog
** 0.0.x
*** 0.0.7

Breaking changes: =phoenix/system= is now an atom, to be found at
=phoenix/!system= - =s:phoenix/system:@phoenix/!system:g= should
migrate you - although, of course, you shouldn't be using
=phoenix/!system= outside the REPL!

Lots of breaking changes to the internal namespaces, to make them
purer - Phoenix is now split into 'batteries included' and 'batteries
removeable' APIs. (See 'Removing the batteries', in the README, for
more details)

Added =(phoenix.core/with-running-system [system (...)] ...)= to make
testing a sub-system much easier.

Thanks to [[https://github.com/krisajenkins][Kris Jenkins]] for his feedback!

*** 0.0.6

Hard-coded path in =lein phoenix uberjar=. I am so so
sorry... :embarrassed:

Couple of other minor internal refactorings, no breaking changes.

*** 0.0.5

=lein phoenix uberjar= was falling foul of Leiningen's new (as of
2.4.0) =:auto-clean= feature - any work done in the Phoenix build was
being cleaned before the JAR was built.

=:auto-clean= still works, but Phoenix now explicitly does it (if
requested) before the build step, then disables it.

*** 0.0.4

Breaking changes - moving to be more compliant with the EDN spec, so
removing namespace-qualified keywords (e.g. =::dep=). These have all
been replaced with (for example) =:phoenix/dep=.

A search replace like =s|::|:phoenix/|g= on your config file should be
sufficient.

Also, symbols in configuration are now automatically quoted, so
explicit quotes should be removed. This is particularly the case for
the CLJS module, where =:mains #{'yourapp.ui.app}= should be replaced
with =:mains #{yourapp.ui.app}=.

Thanks to everyone getting involved in the discussion on the Clojure
mailing list for their suggestions!

*** 0.0.3

Couple of minor bugfixes:

- We no longer run any tests whenever the system is reloaded.
- Small bugfix in uberjar - config values aren't always maps

*** 0.0.2

Added ability to refer to configuration values in environment
variables. Thanks to [[https://github.com/glenjamin][Glen Mailer]] for the suggestion!

Made Phoenix accessible to people who don't use Leiningen by making
=(phoenix/init-phoenix!)= public. It now accepts something that can be
slurped (i.e. either =(io/file ...)= or =(io/resource ...)=), rather
than a path to a resource. Thanks to [[https://github.com/piranha][Alexander Solovyov]] for the
suggestion!

Fixed a bug with the config-file includes that didn't behave as
expected when config files were missing. Again, thanks to [[https://github.com/piranha][Alexander
Solovyov]] for letting me know!

*** 0.0.1

Initial release. Thanks to [[https://github.com/lsnape][Luke Snape]] and [[https://github.com/malcolmsparks][Malcolm Sparks]] for all of
their help and feedback!
